<?php $this->restrict(); ?>
<h1>My Scripts / List</h1>
<?php include $this->getTemplateFile('messages.phtml') ?>

Scripts:
<ul>
    <?php foreach($my_scripts as $script): ?>
    <li>
        <?=$script['name']; ?>
        <a href="?q=my-scripts/edit&script_id=<?=$script['id']?>">Edit script</a>
        <a href="?q=conversation/edit&script_id=<?=$script['id']?>">Edit conversation</a>
    </li>
    <?php endforeach;?>
</ul>

<a href="?q=my-scripts/create">Create</a>